mongo-url = "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/dataon?replicaSet=replication"

namespace-regex = "^dataon.searches"
direct-read-namespaces = ["dataon.searches"]
change-stream-namespaces = ["dataon.searches"]

elasticsearch-urls = ["http://elasticsearch:9200"]
elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000

dropped-collections = false
dropped-databases = false

resume = true

[[mapping]]
namespace = "dataon.searches"
index = "dataon.searches"
type = "_doc"